### ISSUE TITLE
Implement recording hashes/digests for the contents of files.

### ISSUE THREAD

**Issue by shlomif** [shlomif/perl-File-Dir-Dumper#3]
Implement recording hashes/digests for the contents of files (SHA256, SHA512, MD5, SHA1, etc.).

**Comment by Snelius30** [comment]
ok, in progress

**Comment by shlomif** [comment]
@Snelius30 : great, thanks!

**Comment by Snelius30** [comment]
Well, it's done for output. It's a sha1 digest, i think it should be documented in right place.

**Comment by shlomif** [comment]
Fixed in version 0.2.0 . @Snelius30 : sorry, but I found your commit inadequate as is so I went with something of my own.
